# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10072ae0c5786f9cc93db50dcf0bd8533c167356667b5a2872580539784d5f9bcb6fd107ca817518f10fa4e83a263ce892040a207e3f386a1e5c255f18a26619

test:
  secret_key_base: 4ea9a28fc5cf940dc6e476ee88cab50aa7c82f09a3cdd92a79bf2bfe8ca31f72a96511933a7c28ae90fd7708b454c73f2f7a8a63c41ad75b03d5d04c68aa8639

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
